name: 🔒 Privileged
description: You are a Aibaba AI maintainer, or was asked directly by a maintainer to create an issue here. If not, check the other options.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in Aibaba AI! 🚀
        
        If you are not a Aibaba AI maintainer or were not asked directly by a maintainer to create an issue, then please start the conversation in a [Question in GitHub Discussions](https://github.com/aibaba-ai/aibaba-ai/discussions/categories/q-a) instead.
        
        You are a Aibaba AI maintainer if you maintain any of the packages inside of the Aibaba AI repository 
        or are a regular contributor to Aibaba AI with previous merged pull requests.
  - type: checkboxes
    id: privileged
    attributes:
      label: Privileged issue
      description: Confirm that you are allowed to create an issue here.
      options:
        - label: I am a Aibaba AI maintainer, or was asked directly by a Aibaba AI maintainer to create an issue here.
          required: true
  - type: textarea
    id: content
    attributes:
      label: Issue Content
      description: Add the content of the issue here.
